spring:
  datasource:
    url: jdbc:postgres://ec2-184-73-236-170.compute-1.amazonaws.com:5432/dabg4iqngia79h
    username: ugxvdfwvbocgai
    password: 02efd1f552879e6909a324bdf2956a8e34b59506aa37b1972a58e0929c7127ff
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming: 
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialec